FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk-nanoserver-1709 AS build
WORKDIR /src
COPY Learner.Api/Learner.Api.csproj Learner.Api/
RUN dotnet restore Learner.Api/Learner.Api.csproj
COPY . .
WORKDIR /src/Learner.Api
RUN dotnet build Learner.Api.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Learner.Api.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Learner.Api.dll"]
